### ISSUE TITLE
TODO: related to Flot 0.8.1 Upgrade

### ISSUE THREAD

**Issue by duboisp** [duboisp/wet-boew#2]
Related to: https://github.com/wet-boew/wet-boew/issues/2578
Branch: feature-chart
- [x] validate if the issue https://github.com/wet-boew/wet-boew/issues/1217 is fixed
- [x] Investigate about why the height and width are fixed based on the first table. 
  Check the simple-eng.html working example. It look like the charts options are not updated for any subsequent table/charts
- [x] Investigate why the hoverable effet are not working for a pie chart. charts.js line 1393

``` Javascript
    // hoverable
    if (options.piehoverable) {
        pieOptions.grid = {
            hoverable: true
        };
    }
```
